[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "os-hope"
version = "0.1.0"
description = "AI OS Assistant"
authors = [{ name = "" }]
dependencies = []

[tool.setuptools.packages.find]
where = ["src"]

[project.scripts]
oshope-cli = "oshope.interfaces.cli:main"
oshope-web = "oshope.interfaces.streamlit.web:main"