from pydantic import BaseModel, Field
from typing import Literal


class QueryClassificationState(BaseModel):
    """
    Represents the classification of a user's query, including the enhanced query,
    type, confidence score, reasoning, and follow-up requirements.
    """

    original_query_enhanced: str = Field(
        default="",
        description="The enhanced version of the user's original query, rewritten for better clarity and understanding.",
    )

    query_type: Literal["command", "information", "both"] = Field(
        default="both", description="The type of query."
    )

    confidence_score: float = Field(
        default=0.0, ge=0, le=1, description="The confidence score of the classification."
    )

    classification_reasoning: str = Field(
        default="", description="The reasoning behind the classification decision."
    )

    requires_follow_up: bool = Field(
        default=False,
        description="Indicates if a follow-up question is needed for clarification.",
    )

    follow_up_reasoning: str = Field(
        default="",
        description="The reasoning for why a follow-up question is needed, if applicable.",
    )

    generated_follow_up_response: str = Field(
        default="",
        description="The response generated by the LLM for follow-up purposes, if applicable. It should be sent to the user to ask for clarification.",
    )


class QueryClarificationState(BaseModel):
    is_clarification_needed: bool = Field(
        default=False,  # do not put the word error
        description=(
            "Indicates if clarification is needed for the query. "
            "This should be set to true if there are critical missing details in the query or the user did not ask a clear question yet."
        ),
    )

    clarification_reasoning: str = Field(
        default="",
        description="The reasoning behind the need for clarification.",
    )

    generated_response: str = Field(
        default="",
        description=(
            "The response generated by the LLM to ask the user for clarification, if applicable. It should be sent to the user to ask for clarification. "
            "This field should be populated when is_clarification_needed is true."
        ),
    )

    finalized_enhanced_query: str = Field(
        default="",
        description=(
            "The finalized enhanced query after clarification. This should be populated when is_clarification_needed is false, meaning the query is already clear and does not require clarification. "
            "This field should contain an enhanced version of all the user's requests that is clear and ready for processing."
        ),
    )
