from oshope.core.states.cognition_states import *
from oshope.core.states.planning_states import *
from oshope.core.states.execution_states import *
from pydantic import BaseModel, Field
from typing import List


class OSHopeState(BaseModel):
    """
    Represents the state of the OS-HOPE, including any relevant information
    about the current session, user preferences, and system status.
    """
    # ========== Parallel Processing ==========
    parallel_execution_enabled: bool = Field(
        default=False,
        description=(
            "Indicates whether parallel execution of steps is enabled. If set to True, the system will attempt to execute multiple steps concurrently, if possible. "
            "If set to False, the system will execute steps sequentially, one after the other."
        ),
    )

    # ====== RAG ======

    retrieved_memories: List[str] = Field(
        default_factory=list,
        description=(
            "A list of relevant memories retrieved from long-term memory based on the current query and conversation history."
            "This should be populated during the query classification process if RAG is enabled, and can be used to provide additional context for understanding and classifying the user's query."
        ),
    )

    # ========== User query ==========

    turn_num: int = Field(
        default=1,
        description="A counter to keep track of the number of turns in the conversation.",
    )

    original_queries: List[str] = Field(
        default_factory=list,
        description=(
            "A list of the user's original queries. This should include the initial query and any follow-up queries that the user has made for clarification. The most recent query should be at the end of the list."
        ),
    )

    original_queries_enhanced: List[str] = Field(
        default_factory=list,
        description=(
            "A list of enhanced versions of the user's original queries, rewritten for better clarity and understanding."
        ),
    )

    finalized_enhanced_query: str = Field(
        default="",
        description=(
            "The finalized enhanced query after any necessary clarifications. This should be the version of the user's query that is clear and ready for processing, incorporating any enhancements made during classification and clarification."
        ),
    )

    multi_turn_generated_responses: List[str] = Field(
        default_factory=list,
        description=(
            "A list of responses generated by the LLM during multi-turn interactions  "
        ),
    )

    # ========== Query Classification ==========

    query_classification: QueryClassificationState = Field(
        default=QueryClassificationState(), description="The classification of the user's query."
    )

    # This field should be updated by the parsing logic in the query classification node after receiving the response from the LLM
    # The generated response from the LLM must be in the format of QueryClassificationState, so we can directly assign it to this field
    # If an error occurs, retry and generate another response until we get a valid QueryClassificationState response or reach a maximum number of retries to avoid infinite loops
    query_classification_status: str = Field(
        default="pending",
        description="The status of the query classification process (e.g., 'pending', 'completed', 'error').",
    )

    multi_turn_conversation_history: List[dict] = Field(
        default_factory=list,
        description=(
            "A list of dictionaries representing the multi-turn conversation history for query clarification. "
            "Each dictionary will have the following structure: {'turn_num': int, 'user_query': str, 'assistant_response': str}."
        ),
    )

    # ============ Follow-up query & Clarification ============

    # In case the original query requires a follow-up question for clarification
    clarification_attempts: int = Field(
        default=0,
        description="The number of attempts made to clarify the original query.",
    )

    query_clarification: QueryClarificationState = Field(
        default=QueryClarificationState(),
        description="The state of the query clarification process.",
    )

    first_generated_clarification_response: str = Field(
        default="",
        description=(
            "The first response generated by the LLM to ask the user for clarification, if applicable."
        ),
    )
    # =========== Planning ===========

    planning: PlanningState = Field(
        default=PlanningState(),
        description="The execution plan generated for the user's query, including information steps and command steps.",
    )

    planning_status: str = Field(
        default="pending",
        description="The status of the planning process (e.g., 'pending', 'completed', 'error').",
    )

    plan_presented: bool = Field(
        default=False,
        description="Indicates whether the generated plan has been presented to the user for validation.",
    )

    # =========== User Validation ===========

    user_validation_attempts: int = Field(
        default=0,
        description="The number of attempts made to validate the generated plan with the user.",
    )

    user_validation: UserValidationState = Field(
        default=UserValidationState(),
        description="The state of the user validation process for the generated plan.",
    )

    first_generated_validation_response: str = Field(
        default="",
        description=(
            "The first response generated by the LLM to ask the user for validation of the generated plan."
        ),
    )

    user_validation_status: str = Field(
        default="pending",
        description="The status of the user validation process (e.g., 'pending', 'completed', 'error').",
    )

    # =========== ExecutionOrchestrator ===========

    current_step_index: int = Field(
        default=0,
        description=(
            "The index of the current step being executed in the steps list of the PlanningState. This should be updated after each step execution to reflect the next step to execute. "
        ),
    )

    executed_steps: List[str] = Field(
        default_factory=list,
        description="A short summary of the executed(info/command) steps",
    )

    # =========== Step Resolver ===========

    steps_resolver: List[StepResolverState] = Field(
        default_factory=list,
        description=(
            "A list of step resolver states, which represent the resolved steps after replacing any placeholders with actual values from dependencies."
        ),
    )

    steps_resolver_active: bool = Field(
        default=False,
        description=(
            "Indicates whether the step resolver is currently active and processing a step for resolution. "
        ),
    )

    current_resolving_step_index: int = Field(
        default=0,
        description=(
            "The index of the step currently being processed for resolution in the steps list of the StepResolverState."
        ),
    )

    # =========== Command Execution ===========

    command_executions: List[CommandExecution] = Field(
        default_factory=list,
        description=(
            "A list of command execution results, detailing the outcome of each command "
            "that was run as part of fulfilling the user's request."
        ),
    )

    command_execution_status: str = Field(
        default="pending",
        description="The status of the command execution process (e.g., 'pending', 'completed', 'error').",
    )

    # =========== Error Handling ===========

    command_error_handlers: List[CommandErrorHandlerState] = Field(
        default_factory=list,
        description=(
            "A list of command error handler states, which manage the recovery process for failed command executions."
        ),
    )

    num_error_executions: int = Field(
        default=0,
        description=(
            "A counter for the number of command executions that resulted in an error. "
            "This can be used to determine if we should retry executing a command or if we should consider the command as failed after reaching a certain threshold."
        ),
    )

    command_error_handler_active: bool = Field(
        default=False,
        description=(
            "Indicates whether the command error handler is currently active and processing a failed command execution for recovery."
        ),
    )

    # =========== Information Response ===========

    generated_information_responses: List[InformationResponse] = Field(
        default_factory=list,
        description="A list of generated responses to answer the information the user requested",
    )

    generated_information_responses_status: str = Field(
        default="pending",
        description="The status of the information generation process (e.g., 'pending', 'completed', 'error').",
    )

    # =========== Final Response ===========
    generated_final_response: str = Field(
        default="",
        description="The final response generated to be sent to the user after completing all steps of the plan execution. This should be a clear and user-friendly response",
    )

    final_response_status: str = Field(
        default="pending",
        description="The status of the final response process (e.g., 'pending', 'completed', 'error').",
    )

    # =========== Summarization & Memory Extraction ===========
    memory_extraction: SummarizerState = Field(
        default=SummarizerState(),
        description="The state of the summarization process for extracting durable and reusable information to be stored in long-term memory.",
    )

    past_session_summaries: List[str] = Field(
        default_factory=list,
        description=(
            "A list of summaries from past sessions, which can be used for retrieval augmentation in future sessions. "
            "This should be updated after each session to include the summary of that session."
        ),
    )

    execution_time: float = Field(
        default=0.0,
        description=(
            "A timer to keep track of the total execution time of the OS-HOPE."
        ),
    )

    total_retry_wait_time: float = Field(
        default=0.0,
        description=(
            "A timer to keep track of the total wait time spent on retries during llm calls."
        ),
    )
